package com.piger.jspider.model;

public class TbDetailTag {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_detail_tag.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_detail_tag.detail_id
     *
     * @mbggenerated
     */
    private Long detailId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_detail_tag.tag_hash_id
     *
     * @mbggenerated
     */
    private String tagHashId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_detail_tag.id
     *
     * @return the value of tb_detail_tag.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_detail_tag.id
     *
     * @param id the value for tb_detail_tag.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_detail_tag.detail_id
     *
     * @return the value of tb_detail_tag.detail_id
     *
     * @mbggenerated
     */
    public Long getDetailId() {
        return detailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_detail_tag.detail_id
     *
     * @param detailId the value for tb_detail_tag.detail_id
     *
     * @mbggenerated
     */
    public void setDetailId(Long detailId) {
        this.detailId = detailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_detail_tag.tag_hash_id
     *
     * @return the value of tb_detail_tag.tag_hash_id
     *
     * @mbggenerated
     */
    public String getTagHashId() {
        return tagHashId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_detail_tag.tag_hash_id
     *
     * @param tagHashId the value for tb_detail_tag.tag_hash_id
     *
     * @mbggenerated
     */
    public void setTagHashId(String tagHashId) {
        this.tagHashId = tagHashId == null ? null : tagHashId.trim();
    }
}