package com.piger.jspider.model;

public class TbDetailSmallImage {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_detail_small_image.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_detail_small_image.detail_id
     *
     * @mbggenerated
     */
    private Long detailId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_detail_small_image.url
     *
     * @mbggenerated
     */
    private String url;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_detail_small_image.id
     *
     * @return the value of tb_detail_small_image.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_detail_small_image.id
     *
     * @param id the value for tb_detail_small_image.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_detail_small_image.detail_id
     *
     * @return the value of tb_detail_small_image.detail_id
     *
     * @mbggenerated
     */
    public Long getDetailId() {
        return detailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_detail_small_image.detail_id
     *
     * @param detailId the value for tb_detail_small_image.detail_id
     *
     * @mbggenerated
     */
    public void setDetailId(Long detailId) {
        this.detailId = detailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_detail_small_image.url
     *
     * @return the value of tb_detail_small_image.url
     *
     * @mbggenerated
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_detail_small_image.url
     *
     * @param url the value for tb_detail_small_image.url
     *
     * @mbggenerated
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }
}