package com.piger.jspider.model;

import java.util.Date;

public class TbDetail {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_detail.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_detail.title
     *
     * @mbggenerated
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_detail.id_code
     *
     * @mbggenerated
     */
    private String idCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_detail.video_id
     *
     * @mbggenerated
     */
    private String videoId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_detail.big_image
     *
     * @mbggenerated
     */
    private String bigImage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_detail.gmt_create
     *
     * @mbggenerated
     */
    private Date gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_detail.score
     *
     * @mbggenerated
     */
    private Float score;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_detail.user_wanted
     *
     * @mbggenerated
     */
    private Integer userWanted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_detail.user_watched
     *
     * @mbggenerated
     */
    private Integer userWatched;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_detail.user_owned
     *
     * @mbggenerated
     */
    private String userOwned;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_detail.is_del
     *
     * @mbggenerated
     */
    private Boolean isDel;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_detail.id
     *
     * @return the value of tb_detail.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_detail.id
     *
     * @param id the value for tb_detail.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_detail.title
     *
     * @return the value of tb_detail.title
     *
     * @mbggenerated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_detail.title
     *
     * @param title the value for tb_detail.title
     *
     * @mbggenerated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_detail.id_code
     *
     * @return the value of tb_detail.id_code
     *
     * @mbggenerated
     */
    public String getIdCode() {
        return idCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_detail.id_code
     *
     * @param idCode the value for tb_detail.id_code
     *
     * @mbggenerated
     */
    public void setIdCode(String idCode) {
        this.idCode = idCode == null ? null : idCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_detail.video_id
     *
     * @return the value of tb_detail.video_id
     *
     * @mbggenerated
     */
    public String getVideoId() {
        return videoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_detail.video_id
     *
     * @param videoId the value for tb_detail.video_id
     *
     * @mbggenerated
     */
    public void setVideoId(String videoId) {
        this.videoId = videoId == null ? null : videoId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_detail.big_image
     *
     * @return the value of tb_detail.big_image
     *
     * @mbggenerated
     */
    public String getBigImage() {
        return bigImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_detail.big_image
     *
     * @param bigImage the value for tb_detail.big_image
     *
     * @mbggenerated
     */
    public void setBigImage(String bigImage) {
        this.bigImage = bigImage == null ? null : bigImage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_detail.gmt_create
     *
     * @return the value of tb_detail.gmt_create
     *
     * @mbggenerated
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_detail.gmt_create
     *
     * @param gmtCreate the value for tb_detail.gmt_create
     *
     * @mbggenerated
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_detail.score
     *
     * @return the value of tb_detail.score
     *
     * @mbggenerated
     */
    public Float getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_detail.score
     *
     * @param score the value for tb_detail.score
     *
     * @mbggenerated
     */
    public void setScore(Float score) {
        this.score = score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_detail.user_wanted
     *
     * @return the value of tb_detail.user_wanted
     *
     * @mbggenerated
     */
    public Integer getUserWanted() {
        return userWanted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_detail.user_wanted
     *
     * @param userWanted the value for tb_detail.user_wanted
     *
     * @mbggenerated
     */
    public void setUserWanted(Integer userWanted) {
        this.userWanted = userWanted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_detail.user_watched
     *
     * @return the value of tb_detail.user_watched
     *
     * @mbggenerated
     */
    public Integer getUserWatched() {
        return userWatched;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_detail.user_watched
     *
     * @param userWatched the value for tb_detail.user_watched
     *
     * @mbggenerated
     */
    public void setUserWatched(Integer userWatched) {
        this.userWatched = userWatched;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_detail.user_owned
     *
     * @return the value of tb_detail.user_owned
     *
     * @mbggenerated
     */
    public String getUserOwned() {
        return userOwned;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_detail.user_owned
     *
     * @param userOwned the value for tb_detail.user_owned
     *
     * @mbggenerated
     */
    public void setUserOwned(String userOwned) {
        this.userOwned = userOwned == null ? null : userOwned.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_detail.is_del
     *
     * @return the value of tb_detail.is_del
     *
     * @mbggenerated
     */
    public Boolean getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_detail.is_del
     *
     * @param isDel the value for tb_detail.is_del
     *
     * @mbggenerated
     */
    public void setIsDel(Boolean isDel) {
        this.isDel = isDel;
    }
}