package com.piger.jspider.mapper;

import com.piger.jspider.model.TbDetailStar;
import com.piger.jspider.model.TbDetailStarExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TbDetailStarMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_detail_star
     *
     * @mbggenerated
     */
    int countByExample(TbDetailStarExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_detail_star
     *
     * @mbggenerated
     */
    int deleteByExample(TbDetailStarExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_detail_star
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_detail_star
     *
     * @mbggenerated
     */
    int insert(TbDetailStar record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_detail_star
     *
     * @mbggenerated
     */
    int insertSelective(TbDetailStar record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_detail_star
     *
     * @mbggenerated
     */
    List<TbDetailStar> selectByExample(TbDetailStarExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_detail_star
     *
     * @mbggenerated
     */
    TbDetailStar selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_detail_star
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TbDetailStar record, @Param("example") TbDetailStarExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_detail_star
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TbDetailStar record, @Param("example") TbDetailStarExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_detail_star
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TbDetailStar record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_detail_star
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TbDetailStar record);
}