package com.piger.jspider.mapper;

import com.piger.jspider.model.TbDetailSmallImage;
import com.piger.jspider.model.TbDetailSmallImageExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TbDetailSmallImageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_detail_small_image
     *
     * @mbggenerated
     */
    int countByExample(TbDetailSmallImageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_detail_small_image
     *
     * @mbggenerated
     */
    int deleteByExample(TbDetailSmallImageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_detail_small_image
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_detail_small_image
     *
     * @mbggenerated
     */
    int insert(TbDetailSmallImage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_detail_small_image
     *
     * @mbggenerated
     */
    int insertSelective(TbDetailSmallImage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_detail_small_image
     *
     * @mbggenerated
     */
    List<TbDetailSmallImage> selectByExample(TbDetailSmallImageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_detail_small_image
     *
     * @mbggenerated
     */
    TbDetailSmallImage selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_detail_small_image
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TbDetailSmallImage record, @Param("example") TbDetailSmallImageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_detail_small_image
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TbDetailSmallImage record, @Param("example") TbDetailSmallImageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_detail_small_image
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TbDetailSmallImage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_detail_small_image
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TbDetailSmallImage record);
}