package com.piger.jspider.mapper;

import com.piger.jspider.model.TbTag;
import com.piger.jspider.model.TbTagExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TbTagMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_tag
     *
     * @mbggenerated
     */
    int countByExample(TbTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_tag
     *
     * @mbggenerated
     */
    int deleteByExample(TbTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_tag
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_tag
     *
     * @mbggenerated
     */
    int insert(TbTag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_tag
     *
     * @mbggenerated
     */
    int insertSelective(TbTag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_tag
     *
     * @mbggenerated
     */
    List<TbTag> selectByExample(TbTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_tag
     *
     * @mbggenerated
     */
    TbTag selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_tag
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TbTag record, @Param("example") TbTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_tag
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TbTag record, @Param("example") TbTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_tag
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TbTag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_tag
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TbTag record);
}